{
 "title": "Eyeflow Single Station Monitoring",
 "description": "Docker Monitoring Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "station",
    "label": "Station Name",
    "query": {
     "query": "label_values(station_cores, host)"
    }
   },
   {
    "name": "nic",
    "label": "Network Card",
    "query": {
     "query": "label_values(nic_rx{host=~\"$station\"}, nic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Station metrics and alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Customer Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cores{host=~\"$station\"}",
     "legendFormat": "{{customer}}"
    }
   ]
  },
  {
   "title": "Station Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cores{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "NIC IP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nic_ip_info{host=~\"$station\", nic=~\"$nic\"}",
     "legendFormat": "{{ip}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_uptime_info{host=~\"$station\"}",
     "legendFormat": "{{station_uptime}}"
    }
   ]
  },
  {
   "title": "Avg Station Heartbeat",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "avg(time() - station_heartbeat{host=~\"$station\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - station_use_idle{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - ((station_mem_free{host=~\"$station\"} + station_mem_cached{host=~\"$station\"}) / station_mem_total{host=~\"$station\"})",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(ALERTS)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Alerts Details",
   "type": "table",
   "gridPos": { "h": 5, "w": 13, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "ALERTS", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cpu_temp{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_mem_temp{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Process Alert",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(process_missing > 0)", "legendFormat": "{{host}}" }
   ]
  },
  {
   "title": "Process Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 9 },
   "targets": [
    { "expr": "process_active", "legendFormat": "{{process}}" },
    { "expr": "process_cpu", "legendFormat": "{{process}}" },
    { "expr": "process_mem", "legendFormat": "{{process}}" },
    { "expr": "process_pid", "legendFormat": "{{process}}" }
   ]
  },
  {
   "title": "GPU utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_utilization{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GPU memory utilization",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(gpu_memory{host=~\"$station\"} - gpu_mem_free{host=~\"$station\"}) / gpu_memory{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_temperature{host=~\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_power{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Service Reported Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "service_status{host=~\"$station\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Services Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - service_heartbeat{host=~\"$station\"}",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "IP responding Percent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - ping_loss_pct{host=~\"$station\"}",
     "legendFormat": "{{ipaddr}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "nic_rx{host=~\"$station\", nic=~\"$nic\"}",
     "legendFormat": "{{nic}}"
    },
    {
     "expr": "-nic_tx{host=~\"$station\", nic=~\"$nic\"}",
     "legendFormat": "{{nic}}"
    }
   ]
  },
  {
   "title": "Cameras not responding",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count((time() - camera_heartbeat{host=~\"$station\"}) > 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Camera Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(abs((time() - camera_heartbeat{host=~\"$station\"}) - 30) / 120)",
     "legendFormat": "{{camera}}"
    }
   ]
  },
  {
   "title": "Filesystem Utilization Over 10%",
   "type": "table",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_utilization{host=~\"$station\"} > 10",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Station time series and GPU information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GPU in Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU in Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - station_use_idle{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory in Use",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "station_mem_used{host=~\"$station\"} / station_mem_total{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "station_mem_cached{host=~\"$station\"} / station_mem_total{host=~\"$station\"}",
     "legendFormat": "buffer/cache"
    }
   ]
  },
  {
   "title": "GPU Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_name_info{host=~\"$station\"}",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "Station Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_timestamp_info{host=~\"$station\"}",
     "legendFormat": "{{station_timestamp}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cores{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Memory Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 14, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_mem_total{host=~\"$station\"}",
     "legendFormat": "total"
    },
    {
     "expr": "station_mem_free{host=~\"$station\"}",
     "legendFormat": "free"
    },
    {
     "expr": "station_mem_used{host=~\"$station\"}",
     "legendFormat": "used"
    },
    {
     "expr": "station_mem_cached{host=~\"$station\"}",
     "legendFormat": "buff/cache"
    }
   ]
  },
  {
   "title": "GPU Driver",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_driver_info{host=~\"$station\"}",
     "legendFormat": "{{gpu_driver}}"
    }
   ]
  },
  {
   "title": "GPU CUDA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_cuda_info{host=~\"$station\"}",
     "legendFormat": "{{gpu_cuda}}"
    }
   ]
  },
  {
   "title": "GPU Memory",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gpu_memory{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU FAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 9, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_cpu_fan{host=~\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis FAN",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_chassis_fan{host=~\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "station_pci_power{host=~\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCI Temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "station_pci_temp{host=~\"$station\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Station Processes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "station_tasks_running{host=~\"$station\"}",
     "legendFormat": "Processes Running"
    },
    {
     "expr": "station_tasks_stop{host=~\"$station\"}",
     "legendFormat": "Processes Stoped"
    }
   ]
  },
  {
   "title": "GPU Profile",
   "type": "table",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "gpu_fan_percent{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_temperature{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_temp_max{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_temp_slow{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_temp_target{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_power{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_power_limit{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "gpu_power_max{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Station Heartbeat",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - station_heartbeat{host=~\"$station\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Disk Profile",
   "type": "table",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "disk_read_req_persec{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_write_req_persec{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_read_await{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_write_await{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_read_req_queued_persec{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_write_req_queued_persec{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    },
    {
     "expr": "disk_avg_queue{host=~\"$station\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 7, "x": 17, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "agent_version_info{host=~\"$station\"}",
     "legendFormat": "{{agent_version}}"
    }
   ]
  }
 ]
}